// extra genre rows for specific providers, genreId format varies per provider (numeric ids vs full urls)
export interface CustomSection {
  label: string;
  genreId: string;
}

export const CUSTOM_HOME_SECTIONS: Record<string, CustomSection[]> = {
  StreamingCommunity: [
    { label: "Azione", genreId: "4" },
    { label: "Romance", genreId: "15" },
    { label: "Animazione", genreId: "19" },
    { label: "Sci-Fi & Fantasy", genreId: "3" },
    { label: "Crime", genreId: "2" },
    { label: "Horror", genreId: "7" },
    { label: "Korean Drama", genreId: "26" },
    { label: "Reality", genreId: "18" },
  ],
  "StreamingCommunity (EN)": [
    { label: "Action", genreId: "4" },
    { label: "Romance", genreId: "15" },
    { label: "Animation", genreId: "19" },
    { label: "Sci-Fi & Fantasy", genreId: "3" },
    { label: "Crime", genreId: "2" },
    { label: "Horror", genreId: "7" },
    { label: "Korean Drama", genreId: "26" },
    { label: "Reality", genreId: "18" },
  ],
  AnimeUnity: [
    { label: "Isekai", genreId: "53" },
    { label: "Shounen", genreId: "34" },
    { label: "Seinen", genreId: "49" },
    { label: "Slice of Life", genreId: "50" },
    { label: "Mecha", genreId: "38" },
    { label: "Romance", genreId: "17" },
    { label: "Sci-Fi", genreId: "40" },
    { label: "Sport", genreId: "27" },
    { label: "Supernatural", genreId: "42" },
    { label: "Horror", genreId: "3" },
  ],
  CB01: [
    { label: "Azione", genreId: "https://cb01official.uno/category/azione/" },
    { label: "Commedia", genreId: "https://cb01official.uno/category/commedia/" },
    { label: "Horror", genreId: "https://cb01official.uno/category/horror/" },
    { label: "Thriller", genreId: "https://cb01official.uno/category/thriller/" },
    { label: "Romantico", genreId: "https://cb01official.uno/category/sentimentale/" },
    { label: "Fantascienza", genreId: "https://cb01official.uno/category/fantascienza/" },
    { label: "Animazione", genreId: "https://cb01official.uno/category/animazione/" },
  ],
  Ridomovies: [
    { label: "Action", genreId: "action" },
    { label: "Comedy", genreId: "comedy" },
    { label: "Horror", genreId: "horror" },
    { label: "Romance", genreId: "romance" },
    { label: "Thriller", genreId: "thriller" },
    { label: "Sci-Fi", genreId: "sci-fi" },
    { label: "Crime", genreId: "crime" },
    { label: "Animation", genreId: "animation" },
  ],
  Fanpelis: [
    { label: "Acción", genreId: "accion" },
    { label: "Comedia", genreId: "comedia" },
    { label: "Terror", genreId: "terror" },
    { label: "Romance", genreId: "romance" },
    { label: "Suspenso", genreId: "suspense" },
    { label: "Ciencia Ficción", genreId: "ciencia-ficcion" },
    { label: "Crimen", genreId: "crimen" },
    { label: "Animación", genreId: "animacion" },
  ],
  // getGenre maps to /generos/{slug}, straight off the site's own genre menu
  Pelisplusto: [
    { label: "Acción", genreId: "generos/accion" },
    { label: "Comedia", genreId: "generos/comedia" },
    { label: "Terror", genreId: "generos/terror" },
    { label: "Romance", genreId: "generos/romance" },
    { label: "Suspense", genreId: "generos/suspense" },
    { label: "Ciencia Ficción", genreId: "generos/ciencia-ficcion" },
    { label: "Crimen", genreId: "generos/crimen" },
    { label: "Animación", genreId: "generos/animacion" },
  ],
  HDFilme: [
    { label: "Action", genreId: "https://hdfilme.win/action/" },
    { label: "Komödie", genreId: "https://hdfilme.win/komodie/" },
    { label: "Horror", genreId: "https://hdfilme.win/horror/" },
    { label: "Romantik", genreId: "https://hdfilme.win/romantik/" },
    { label: "Thriller", genreId: "https://hdfilme.win/thriller/" },
    { label: "Sci-Fi", genreId: "https://hdfilme.win/sci-fi/" },
    { label: "Krimi", genreId: "https://hdfilme.win/krimi/" },
    { label: "Animation", genreId: "https://hdfilme.win/animation/" },
  ],
  // id format is "Name|catid", catid comes straight off the site's own genre menu
  Kidraz: [
    { label: "Action", genreId: "Action|1" },
    { label: "Comédie", genreId: "Comédie|6" },
    { label: "Horreur", genreId: "Horreur|9" },
    { label: "Thriller", genreId: "Thriller|12" },
    { label: "Science-Fiction", genreId: "Science-Fiction|11" },
    { label: "Policier", genreId: "Policier|10" },
    { label: "Fantastique", genreId: "Fantastique|8" },
    { label: "Aventure", genreId: "Aventure|4" },
  ],
  PelisflixHD: [
    { label: "Acción", genreId: "https://pelisflixhd.win/genero/accion" },
    { label: "Comedia", genreId: "https://pelisflixhd.win/genero/comedia" },
    { label: "Terror", genreId: "https://pelisflixhd.win/genero/terror" },
    { label: "Romance", genreId: "https://pelisflixhd.win/genero/romance" },
    { label: "Suspenso", genreId: "https://pelisflixhd.win/genero/suspense" },
    { label: "Ciencia Ficción", genreId: "https://pelisflixhd.win/genero/ciencia-ficcion" },
    { label: "Crimen", genreId: "https://pelisflixhd.win/genero/crimen" },
    { label: "Animación", genreId: "https://pelisflixhd.win/genero/animacion" },
  ],
  // getGenre maps to /category/{slug}, straight off the site's own genre list
  AnyMovie: [
    { label: "Action", genreId: "action" },
    { label: "Comedy", genreId: "comedy" },
    { label: "Horror", genreId: "horror" },
    { label: "Romance", genreId: "romance" },
    { label: "Thriller", genreId: "thriller" },
    { label: "Science Fiction", genreId: "science-fiction" },
    { label: "Crime", genreId: "crime" },
    { label: "Animation", genreId: "animation" },
  ],
  "Cuevana 3": [
    { label: "Acción", genreId: "accion" },
    { label: "Comedia", genreId: "comedia" },
    { label: "Terror", genreId: "terror" },
    { label: "Romance", genreId: "romance" },
    { label: "Suspenso", genreId: "suspense" },
    { label: "Ciencia Ficción", genreId: "ciencia-ficcion" },
    { label: "Crimen", genreId: "crimen" },
    { label: "Animación", genreId: "animacion" },
  ],
  // same numeric scheme as TMDB, pulled straight from the site's own api/genres endpoint
  Einschalten: [
    { label: "Action", genreId: "28" },
    { label: "Komödie", genreId: "35" },
    { label: "Horror", genreId: "27" },
    { label: "Liebesfilm", genreId: "10749" },
    { label: "Thriller", genreId: "53" },
    { label: "Science Fiction", genreId: "878" },
    { label: "Krimi", genreId: "80" },
    { label: "Animation", genreId: "16" },
  ],
  Filmo: [
    { label: "Action", genreId: "action" },
    { label: "Comedy", genreId: "comedy" },
    { label: "Horror", genreId: "horror" },
    { label: "Romance", genreId: "romance" },
    { label: "Thriller", genreId: "thriller" },
    { label: "Science Fiction", genreId: "science-fiction" },
    { label: "Crime", genreId: "crime" },
    { label: "Animation", genreId: "animation" },
  ],
  // kids' cartoon site organized by network/studio brand rather than genre
  "La Cartoons": [
    { label: "Nickelodeon", genreId: "1" },
    { label: "Cartoon Network", genreId: "2" },
    { label: "Hanna Barbera", genreId: "4" },
    { label: "Disney", genreId: "5" },
    { label: "Warner Channel", genreId: "6" },
    { label: "Marvel", genreId: "7" },
  ],
  MEGAKino: [
    { label: "Action", genreId: "/action/" },
    { label: "Comedy", genreId: "/comedy/" },
    { label: "Horror", genreId: "/horror/" },
    { label: "Romance", genreId: "/romance/" },
    { label: "Thriller", genreId: "/thriller/" },
    { label: "Science Fiction", genreId: "/science-fiction/" },
    { label: "Crime", genreId: "/crime/" },
    { label: "Fantasy", genreId: "/fantasy/" },
  ],
  "Series Turcas": [
    { label: "Acción", genreId: "/generos/accion/" },
    { label: "Comedia", genreId: "/generos/comedia/" },
    { label: "Romance", genreId: "/generos/romance/" },
    { label: "Thriller", genreId: "/generos/thriller/" },
    { label: "Crimen", genreId: "/generos/crimen/" },
    { label: "Drama", genreId: "/generos/drama/" },
    { label: "Misterio", genreId: "/generos/misterio/" },
    { label: "Aventura", genreId: "/generos/aventura/" },
  ],
  SeriesFlix: [
    { label: "Acción", genreId: "accion" },
    { label: "Comedia", genreId: "comedia" },
    { label: "Terror", genreId: "terror" },
    { label: "Aventura", genreId: "aventura" },
    { label: "Ciencia Ficción", genreId: "ciencia-ficcion" },
    { label: "Crimen", genreId: "crimen" },
    { label: "Animación", genreId: "animacion" },
    { label: "Drama", genreId: "drama" },
  ],
  "TMDB (ITA)": [
    { label: "Azione", genreId: "28" },
    { label: "Commedia", genreId: "35" },
    { label: "Horror", genreId: "27" },
    { label: "Romance", genreId: "10749" },
    { label: "Thriller", genreId: "53" },
    { label: "Fantascienza", genreId: "878" },
    { label: "Crime", genreId: "80" },
    { label: "Animazione", genreId: "16" },
  ],
  HiAnime: [
    { label: "Isekai", genreId: "isekai" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Slice of Life", genreId: "slice-of-life" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Supernatural", genreId: "supernatural" },
    { label: "Psychological", genreId: "psychological" },
  ],
  AnimeWorld: [
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Slice of Life", genreId: "slice-of-life" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Fantasy", genreId: "fantasy" },
    { label: "Sci-Fi", genreId: "sci-fi" },
    { label: "Psychological", genreId: "psychological" },
  ],
  AniWorld: [
    { label: "Shounen", genreId: "fighting-shounen" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Slice of Life", genreId: "alltagsleben" },
    { label: "Fantasy", genreId: "fantasy" },
    { label: "Sci-Fi", genreId: "scifi" },
    { label: "Romance", genreId: "romanze" },
    { label: "Sport", genreId: "sport" },
  ],
  Anikoto: [
    { label: "Isekai", genreId: "isekai" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Psychological", genreId: "psychological" },
    { label: "Sci-Fi", genreId: "sci-fi" },
    { label: "Supernatural", genreId: "supernatural" },
  ],
  TioAnime: [
    { label: "Mecha", genreId: "mecha" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Shoujo", genreId: "shoujo" },
    { label: "Romance", genreId: "romance" },
    { label: "Sobrenatural", genreId: "sobrenatural" },
    { label: "Terror", genreId: "terror" },
    { label: "Fantasía", genreId: "fantasia" },
  ],
  Latanime: [
    { label: "Mecha", genreId: "mecha" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Shonen", genreId: "shonen" },
    { label: "Shojo", genreId: "shojo" },
    { label: "Harem", genreId: "harem" },
    { label: "Sobrenatural", genreId: "sobrenatural" },
    { label: "Psicológico", genreId: "psicologico" },
    { label: "Recuerdos de la Vida", genreId: "recuerdos-de-la-vida" },
  ],
  AnimeSaturn: [
    { label: "Isekai", genreId: "isekai" },
    { label: "Shounen", genreId: "shounen" },
    { label: "Seinen", genreId: "seinen" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Harem", genreId: "harem" },
    { label: "Psicologico", genreId: "psicologico" },
    { label: "Soprannaturale", genreId: "soprannaturale" },
    { label: "Slice of Life", genreId: "slice-of-life" },
  ],
  // genreId here is a real AniList genre name (its own getGenre() filters catalogAnime by it directly),
  // not a tag like "Isekai" - those return zero results. Picked to not repeat the 5 genres already on its own home
  AnimeX: [
    { label: "Adventure", genreId: "Adventure" },
    { label: "Drama", genreId: "Drama" },
    { label: "Sci-Fi", genreId: "Sci-Fi" },
    { label: "Slice of Life", genreId: "Slice of Life" },
    { label: "Mecha", genreId: "Mecha" },
    { label: "Mystery", genreId: "Mystery" },
    { label: "Horror", genreId: "Horror" },
    { label: "Thriller", genreId: "Thriller" },
  ],
  AnimeAV1: [
    { label: "Acción", genreId: "accion" },
    { label: "Aventuras", genreId: "aventuras" },
    { label: "Comedia", genreId: "comedia" },
    { label: "Drama", genreId: "drama" },
    { label: "Fantasía", genreId: "fantasia" },
    { label: "Romance", genreId: "romance" },
    { label: "Ciencia Ficción", genreId: "ciencia-ficcion" },
    { label: "Sobrenatural", genreId: "sobrenatural" },
    { label: "Isekai", genreId: "isekai" },
    { label: "Terror", genreId: "terror" },
  ],
  // genreId maps to /xfsearch/manga_genre/{name}/, straight off the site's own "Par Genre" menu
  FrenchManga: [
    { label: "Action", genreId: "Action" },
    { label: "Comédie", genreId: "Comédie" },
    { label: "Drame", genreId: "Drame" },
    { label: "Mystère", genreId: "Mystère" },
    { label: "Fantastique", genreId: "Fantastique" },
    { label: "Science-Fiction", genreId: "Science-Fiction" },
    { label: "Aventure", genreId: "Aventure" },
    { label: "Romance", genreId: "Romance" },
  ],
  // genreId maps to /genre/{name}/, straight off the site's own "Anime par genre" menu
  VostFree: [
    { label: "Action", genreId: "Action" },
    { label: "Aventure", genreId: "Aventure" },
    { label: "Comédie", genreId: "Comédie" },
    { label: "Drame", genreId: "Drame" },
    { label: "Fantasy", genreId: "Fantasy" },
    { label: "Surnaturel", genreId: "Surnaturel" },
    { label: "Shonen", genreId: "Shonen" },
    { label: "Romance", genreId: "Romance" },
  ],
  // genreId maps to /film-en-streaming/{slug}/, straight off the site's own genre menu
  Wiflix: [
    { label: "Action", genreId: "action" },
    { label: "Comédie", genreId: "comedie" },
    { label: "Horreur", genreId: "horreur" },
    { label: "Thriller", genreId: "thriller" },
    { label: "Aventure", genreId: "aventure" },
    { label: "Drame", genreId: "drame" },
    { label: "Fantastique", genreId: "fantastique" },
    { label: "Science Fiction", genreId: "science-fiction" },
  ],
  // same DLE engine/url scheme as Wiflix, slugs come straight off the site's own "Par Genre" menu
  FrenchStream: [
    { label: "Action", genreId: "actions" },
    { label: "Comédie", genreId: "comedies" },
    { label: "Horreur", genreId: "epouvante-horreurs" },
    { label: "Romance", genreId: "romances" },
    { label: "Thriller", genreId: "thrillers" },
    { label: "Science Fiction", genreId: "science-fictions" },
    { label: "Policier", genreId: "policiers" },
    { label: "Animation", genreId: "animations" },
  ],
  // getGenre passes id straight through as with_genres[], these are plain TMDB genre ids
  Vuflix: [
    { label: "Action", genreId: "28" },
    { label: "Comedy", genreId: "35" },
    { label: "Horror", genreId: "27" },
    { label: "Romance", genreId: "10749" },
    { label: "Thriller", genreId: "53" },
    { label: "Sci-Fi", genreId: "878" },
    { label: "Crime", genreId: "80" },
    { label: "Animation", genreId: "16" },
  ],
  // getGenre maps to /tag/{slug}/, straight off the site's own tag cloud
  AnimeToast: [
    { label: "Action", genreId: "action" },
    { label: "Comedy", genreId: "comedy" },
    { label: "Drama", genreId: "drama" },
    { label: "Fantasy", genreId: "fantasy" },
    { label: "Romance", genreId: "romance" },
    { label: "Harem", genreId: "harem" },
    { label: "Mecha", genreId: "mecha" },
    { label: "Supernatural", genreId: "supernatural" },
  ],
  // getGenre() takes a full url directly, baseUrl is stale so these point at the site's real current domain
  GuardaFlix: [
    { label: "Azione", genreId: "https://guardaplay.info/category/azione/" },
    { label: "Avventura", genreId: "https://guardaplay.info/category/avventura/" },
    { label: "Commedia", genreId: "https://guardaplay.info/category/commedia/" },
    { label: "Dramma", genreId: "https://guardaplay.info/category/dramma/" },
    { label: "Horror", genreId: "https://guardaplay.info/category/horror/" },
    { label: "Thriller", genreId: "https://guardaplay.info/category/thriller/" },
    { label: "Fantascienza", genreId: "https://guardaplay.info/category/fantascienza/" },
    { label: "Fantasy", genreId: "https://guardaplay.info/category/fantasy/" },
  ],
  GuardaSerie: [
    { label: "Commedia", genreId: "https://guardoserie.college/commedia/" },
    { label: "Dramma", genreId: "https://guardoserie.college/dramma/" },
    { label: "Crime", genreId: "https://guardoserie.college/crime/" },
    { label: "Mistero", genreId: "https://guardoserie.college/mistero/" },
    { label: "Romance", genreId: "https://guardoserie.college/romance/" },
    { label: "Animazione", genreId: "https://guardoserie.college/animazione/" },
    { label: "Famiglia", genreId: "https://guardoserie.college/famiglia/" },
    { label: "Western", genreId: "https://guardoserie.college/western/" },
  ],
};
